function [classes, classes2, posTags, objname_syns] = VOCoptsClasses(VOCyear)

if nargin < 1, VOCyear = []; end

% {'concept name', 'its nickname', 'its parts-of-speech tag', 'its synonyms'}
classes_withPOS={...
    {'aeroplane', 'plane', 'NOUN', {'aeroplane', 'airplane', 'aircraft'}},...
    {'bicycle' , 'bike', 'NOUN',{'bicycle'}},...
    {'bird', 'bird', 'NOUN',{'bird'}},...
    {'boat', 'boat', 'NOUN',{'boat'}},...
    {'bottle', 'bottle', 'NOUN',{'bottle'}},...
    {'bus', 'bus', 'NOUN',{'bus'}},...
    {'car', 'car', 'NOUN',{'car'}},...
    {'cat', 'cat', 'NOUN',{'cat'}},...
    {'chair', 'chair', 'NOUN',{'chair'}},...
    {'cow', 'cow', 'NOUN',{'cow'}},...
    {'diningtable', 'table', 'NOUN',{'diningtable', 'table'}},...
    {'dog', 'dog', 'NOUN',{'dog'}},...
    {'horse', 'horse', 'NOUN',{'horse'}},...
    {'motorbike', 'mbike', 'NOUN',{'motorbike', 'motorcycle', 'moped', 'scooter'}},...
    {'person', 'person', 'NOUN',{'person'}},...
    {'pottedplant', 'plant', 'NOUN',{'pottedplant', 'houseplant', 'flowerpot', 'plantpot'}},...
    {'sheep', 'sheep', 'NOUN',{'sheep'}},...
    {'sofa', 'sofa', 'NOUN',{'sofa'}},...
    {'train', 'train', 'NOUN',{'train'}},...
    {'tvmonitor', 'tv', 'NOUN',{'tv', 'monitor', 'television'}},...
    {'jumping', 'jump', 'VERB',{'jumping'}},...
    {'phoning', 'phone', 'VERB',{'phoning'}},...        
    {'walking', 'walk', 'VERB',{'walking'}},...
    {'running', 'run', 'VERB',{'running'}},...
    {'takingphoto', 'photo', 'VERB',{'photographer'}},...
    {'road', 'road', 'NOUN',{'road'}},... 
    {'florist', 'florist', 'NOUN',{'florist'}},... 
    {'cloister', 'cloister', 'NOUN',{'cloister'}},... 
    {'buffet', 'buffet', 'NOUN',{'buffet'}},... 
    {'pantry', 'pantry', 'NOUN',{'pantry'}},... 
    {'nursery', 'nursery', 'NOUN',{'nursery'}},... 
    {'garage', 'garage', 'NOUN',{'garage'}},... 
    {'elevator', 'elevator', 'NOUN',{'elevator'}},...     
    {'bookstore', 'bookstore', 'NOUN',{'bookstore'}},... 
    {'closet', 'closet', 'NOUN',{'closet'}},...     
    {'subway', 'subway', 'NOUN',{'subway'}},... 
    {'bowling', 'bowling', 'NOUN',{'bowling'}},... 
    {'casino', 'casino', 'NOUN',{'casino'}},... 
    {'lobby', 'lobby', 'NOUN',{'lobby'}},... 
    {'mall', 'mall', 'NOUN',{'mall'}},... 
    {'pedestrian', 'pedestrian', 'NOUN',{'pedestrian'}},... 
    {'giraffe', 'giraffe', 'NOUN',{'giraffe'}},... 
    {'swan', 'swan', 'NOUN',{'swan'}},... 
    {'boxing', 'boxing', 'VERB',{'boxing'}},... 
    {'swinging', 'swinging', 'VERB',{'swinging'}},... 
    {'eating', 'eating', 'VERB',{'eating'}},... 
    {'fighting', 'fighting', 'VERB',{'fighting'}},... 
    {'kissing', 'kissing', 'VERB',{'kissing'}},... 
    {'adidas', 'adidas', 'NOUN',{'adidas'}},...         
    {'rainbow', 'rainbow', 'NOUN',{'rainbow'}},... 
    {'breakfast', 'breakfast', 'NOUN',{'breakfast'}},...
    {'eclipse', 'eclipse', 'NOUN',{'eclipse'}},...
    {'reading', 'read', 'VERB',{'reading'}},...      
    {'competing', 'competing', 'VERB',{'competing'}},... 
    {'praying', 'praying', 'VERB',{'praying'}},... 
    {'climbing', 'climbing', 'VERB',{'climbing'}},...    
    {'swimming', 'swimming', 'VERB',{'swimming'}},...    
    {'stress', 'stress', 'NOUN',{'stress'}},...        
    {'gandhi', 'gandhi', 'NOUN',{'gandhi', 'Gandhi'}},...
    {'hitler', 'hitler', 'NOUN',{'hitler', 'Hitler'}},...   
    {'cancer', 'cancer', 'NOUN',{'cancer'}},...
    {'happy', 'happy', 'ADJ',{'happy'}},...
    {'angry', 'angry', 'ADJ',{'angry'}},...
    {'shiny', 'shiny', 'ADJ',{'shiny'}},...        
    {'sterile', 'sterile', 'ADJ',{'sterile'}},...
    {'dirty', 'dirty', 'ADJ',{'dirty'}},...     
    {'iran', 'iran', 'NOUN',{'iran', 'Iran'}},... 
    {'germany', 'germany', 'NOUN',{'germany', 'Germany'}},...         
    {'japan', 'japan', 'NOUN',{'japan', 'Japan'}},...    
    {'india', 'india', 'NOUN',{'india', 'India', 'Bharat', }},...        
    {'france', 'france', 'NOUN',{'france', 'France'}},...    
    {'tehran', 'tehran', 'NOUN',{'tehran', 'Tehran'}},...    
    {'christmas', 'christmas', 'NOUN',{'christmas', 'Christmas'}},...    
    {'diwali', 'diwali', 'NOUN',{'diwali', 'Diwali', 'Navratri', 'Dussehra'}},...    
    {'bakery', 'bakery', 'NOUN',{'bakery'}},...
    {'kitchen', 'kitchen', 'NOUN',{'kitchen'}},...
    {'classroom', 'classroom', 'NOUN',{'classroom'}},...
    {'doctor', 'doctor', 'NOUN',{'doctor'}},...
    {'mother', 'mother', 'NOUN',{'mother'}},...
    {'teaching', 'teaching', 'VERB',{'teaching', 'instructing'}},...
    {'apple', 'apple', 'NOUN',{'apple'}},...
    {'wedding', 'wedding', 'NOUN',{'wedding'}},...
    {'concert', 'concert', 'NOUN',{'concert'}},...
    {'vacation', 'vacation', 'NOUN',{'vacation'}},... 
    {'tiger', 'tiger', 'NOUN',{'tiger'}},...    
    {'elephant', 'elephant', 'NOUN',{'elephant'}},...
    {'awkward', 'awkward', 'ADJ',{'awkward'}},...
    {'natural', 'natural', 'ADJ',{'natural'}},...
    {'hiking', 'hiking', 'VERB',{'hiking'}},...
    {'diving', 'diving', 'VERB',{'diving'}},...
    {'exercise', 'exercise', 'NOUN',{'exercise'}},...
    {'flower', 'flower', 'NOUN',{'flower'}},...
    {'food', 'food', 'NOUN',{'food'}},...
    {'symmetrical', 'symmetrical', 'ADJ',{'symmetrical'}},...
    {'digging', 'digging', 'VERB',{'digging'}},...
    {'pavement', 'pavement', 'NOUN',{'pavement'}},...
    {'research', 'research', 'NOUN',{'research'}},...
    {'scary', 'scary', 'ADJ',{'scary'}},...
    {'timecar', 'timecar', 'NOUN',{'timecar'}},...     
    }; 
%{'popular', 'popular', 'NOUN'},...
%{'ridinghorse', 'ridehorse', 'VERB'},...
% %{'takingphoto', 'photo', 'VERB',{'photographing'}},...
%{'tree', 'tree', 'NOUN',{'tree', 'trees'}},...
%{'laundromat', 'laundromat', 'NOUN',{'laundromat'}},... 
%{'hairsalon', 'hairsalon', 'NOUN',{'hairsalon'}},... 
%{'terrorist', 'terrorist', 'NOUN',{'terrorist'}},... 
%{'juggling', 'juggling', 'VERB',{'juggling'}},...     

numcls = numel(classes_withPOS);
[classes, classes2, posTags, objname_syns] = deal(cell(numcls,1));
for f=1:numcls
    classes{f}=classes_withPOS{f}{1};
    classes2{f}=classes_withPOS{f}{2};
    posTags{f}=classes_withPOS{f}{3};
    objname_syns{f}=classes_withPOS{f}{4}; 
end

%classes = textread('/lustre/sdivvala/visualSubcat_results/Pascal_VOC_tmp/data/VOC1009/ImageSets/Main/class.txt', '%s');
%classes2 = [];

%{
classes={...
    'aeroplane'
    'bicycle' 
    'bird'
    'boat'
    'bottle'
    'bus'
    'car'
    'cat'
    'chair'
    'cow'
    'diningtable'
    'dog'
    'horse'
    'motorbike'
    'person'
    'pottedplant'
    'sheep'
    'sofa'
    'train'
    'tvmonitor'
    'elephant'
    'happy'
    'tehran'
    'diwali'
    'jumping'
    'phoning'
    'reading'
    'running'
    'ridingbike'
    'ridinghorse'
    'walking'
    'photographing'
    'apple'
    'tiger'
    'popular'};

%dancing,birthday,eating,opening

posTags={...
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'NOUN'
    'ADJ'
    'NOUN'
    'NOUN'
    'VERB'
    'VERB'
    'VERB'
    'VERB'
    'VERB'
    'VERB'
    'VERB'
    'VERB'
    'NOUN'
    'NOUN'
    'NOUN'};                
    
classes2={...
    'plane'
    'bike'
    'bird'
    'boat'
    'bottle'
    'bus'
    'car'
    'cat'
    'chair'
    'cow'
    'table'
    'dog'
    'horse'
    'mbike'
    'person'
    'plant'
    'sheep'
    'sofa'
    'train'
    'tv'
    'elphnt'
    'happy'
    'tehran'
    'diwali'
    'jumping'
    'phoning'
    'reading'
    'running'
    'walking'
    'apple'
    'tiger'
    'popular'};
%}



